name: BuildnPub_WLGate
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: npm install
    - name: build and publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx electron-forge publish --platform linux --arch=x64

  build_on_mac:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: setup appdmg
      run: |
        python3 -m pip install setuptools
        npm install -g appdmg@0.6.6
    - name: install dependencies
      run: npm install
    - name: build and publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx electron-forge publish --arch=universal


  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: npm install
    - name: build and publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx electron-forge publish
